<div class="grid_12">
<h1>Background</h1> 

<p>Xandora File Analyzer (Code Name “xandora.net”) offers a free service
whereby its customers may submit sample files containing suspected threats for
analysis by the xandora.net automated threat analysis system (“xandora.net”). Further
information on the xandora.net is available from http://xandora.net</p>

<p>By submitting a sample file for analysis by xandora.net (“Analysis”), you agree to
be bound by these terms and conditions (“Agreement”).</p>

<h1>Submitting a Sample File for Analysis</h1>

<p>You must submit a copy of your sample file (“File”) to xandora.net for analysis by
the xandora.net System using the methods of submission specified by xandora.net from
time to time.</p>

<p>You warrant that, in submitting a File to xandora.net for analysis, you have the
requisite rights to submit the file to xandora.net and that submitting the file
will not breach the rights (including, without limitation, any intellectual
property rights) of any third party.</p>

<h1>Analysis</h1>

<p>The Analysis will take place on dates and times determined by xandora.net. xandora.net
does not warrant that it will commence or complete the Analysis of the File
within any particular time frame. However, xandora.net will use its reasonable
endeavours to complete the Analysis that xandora.net receives the File and any
other information which xandora.net requests from you to complete its analysis.</p>

<h1>Use of Reports</h1>

<p>Upon Analysing the File, a report will be generated (“Report”). All content
contained in the Report is the copyrighted work of xandora.net and its affiliates.
xandora.net may reuse the Report in any way it sees fit in its sole and absolute
discretion.</p>

<p>You are permitted to reprint the whole or part of the Report, provided that the
reprint:</p>

<ol style="list-style-type:lower-alpha;">
<li>clearly and prominently states that the content was created by xandora.net; 
<li>contains a link to xandora.net.net; and 
<li>includes the following copyright
attribution statement: “Reprinted with permission from xandora.net.”
</ol>

<h1>Fees</h1>

<p>Unless otherwise specified by xandora.net to the contrary, the Analysis and Reports
are provided free of charge.</p>

<h1>Your Indemnity</h1>

<p>You agree to indemnify xandora.net and keep xandora.net indemnified against any loss,
cost, expense or damage (including full legal costs) which xandora.net suffers or
incurs as a direct or indirect result of:</p>

<ol style="list-style-type:lower-alpha;">
<li>any breach of this Agreement by you; or 
<li>any action, claim, proceeding or demand instituted or made against xandora.net
by a third party claiming that xandora.net’s analysis and/or use of the File
infringes any rights of the third party.
</ol>

<h1>Publicity</h1>

<p>You agree that xandora.net may acknowledge your use of the xandora.net System publicly
and may publish details of any Analysis of the File on its website and/or
through any media releases.</p>

<h1>Intellectual Property Rights</h1>

<p>For the purposes of this Agreement, the term “intellectual property rights”
will mean all intellectual property rights of any kind whatsoever throughout
the world, whether existing now or in the future, including, without
limitation, all rights in copyright, trade marks, patents and designs (whether
or not such rights are registered or not).</p>

<p>You acknowledge and agree that the intellectual property rights and all rights
in any test results, Reports or other materials generated by xandora.net under this
Agreement or in relation to this Agreement will be owned by xandora.net and/or its
affiliates. You agree that you have no claim or ownership over such
intellectual property rights.</p>

<h1>Limitation of Liability</h1>

<p>You hereby acknowledge that the analysis and report generated by the xandora.net
System cannot be guaranteed error free or free of any defects. In particular,
xandora.net does not guarantee that the xandora.net System will detect and/or report
all threats or correctly detect or report any threat contained in any File
submitted by you. You agree that you will use your independent judgement in
your analysis of the contents of any Report and will not rely on the results of
any Report for any purpose. You make use of the contents of any Report at your
own risk.</p>

<p>In the event any terms, conditions, representations or warranties are implied
by statute, common law or equity (“Prescribed Terms”) into these terms and
conditions which cannot be lawfully excluded, such Prescribed Terms will apply,
save that xandora.net’s liability for breach of any such Prescribed Terms will be
limited, to the extent permitted by law, at xandora.net’s option, to any one or
more of the following:</p>

<ol style="list-style-type:lower-alpha;">
<li>in the case of goods: 
<ol style="list-style-type:lower-roman;">
    <li>the replacement of the goods to which the breach
    relates or the supply of equivalent goods; 
    <li>the repair of the goods; 
    <li>the payment of the cost of replacing the goods or of acquiring equivalent
    goods; or 
    <li>the payment of the cost of having the goods repaired; and 
</ol>
<li>in the case of services: 
<ol style="list-style-type:lower-roman;">
    <li>the supplying of the services again; or 
    <li>the payment of the cost of having the services supplied again.
</ol>
</ol>

<p>If xandora.net’s liability for breach of any Prescribed Terms are capable of
exclusion, they are hereby excluded to the fullest extent permitted by law.

<p>Except as provided by the Prescribed Terms (if any), which are not capable of
exclusion or limitation, or as expressly set out in these terms and conditions:

(a) xandora.net makes no warranties in relation to the Analysis or the content of
any Reports, including warranties as to the performance or fitness for purpose
of the Analysis or the Reports (other than xandora.net is entitled to grant to you
the right to use the xandora.net as set out in these terms and conditions);
and (b) you will not under any circumstances have any cause of action against,
or right to claim or recover from xandora.net for or in respect of any loss, damage
or injury arising from the use of the xandora.net, any Analysis, any Report,
or any breach of these terms and conditions.

<p>xandora.net will not be liable for any indirect or consequential damages (including
loss of profits, loss of data or economic loss) arising out of a breach of
these terms and conditions, arising from your use of the xandora.net or
arising out of the supply of a defective Report.

<p>You acknowledge that you have exercised your independent judgment in using the
xandora.net and any Report and have not relied upon any representations made
by xandora.net which have not been stated expressly in these terms and conditions
or upon any descriptions or illustrations or specifications contained in any
document, including catalogues or publicity material produced by xandora.net.

<h1>General Clauses</h1>

<p>No failure or omission to carry out or observe any term of this Agreement will
give rise to a claim by you against xandora.net or result in a breach of this
Agreement by xandora.net if such failure or omission arises by reason of delay or
inability to perform caused by technology failure, communications failure, war,
whether declared or not, civil rebellion, strike, fire, storm or other severe
action of the elements, accident, government or statutory restriction or from
other similar causes which are unavoidable or beyond the reasonable control of
xandora.net.

<p>A provision of or a right created under this Agreement may not be waived or
varied except in writing signed by the party or parties to be bound by the
waiver or variation. No single or partial exercise by any party of any right,
power or remedy under this Agreement will preclude any other or further
exercise of that or any other right, power or remedy. The rights, powers or
remedies provided in this Agreement are cumulative with and not exclusive of
any rights, powers or remedies provided independently of this Agreement.

<p>xandora.net may transfer its rights and obligations under this Agreement to any
person with or without notice to you. You must not assign your rights or
obligations under this Agreement without xandora.net’s prior written consent (which
may be withheld).

<h1>Privacy Policy</h1>

<p>This policy sets out the privacy practices of xandora.net (“xandora.net”) in
connection with all of the products, services and websites offered by xandora.net
(collectively, “services”).</p>

<h1>Collection and use of personal information</h1>

<p>xandora.net does not collect any personal data about you on this website or in
connection with any other service, apart from information which you volunteer
(for example by e-mailing us, by submitting a sample file to us, or by using
our online feedback form). When you submit a sample file to xandora.net, we may
collect information including your name and contact details.</p>

<p>If xandora.net has your email address, we may contact you by email to advise you of
product updates, subscribe you to our newsletter or offer you xandora.net or third
party products. xandora.net may also contact you in relation to customer support
queries which you lodge.</p>

<p>Your personal data may also be anonymous and used for statistical purposes.</p>

<h1>Your rights regarding data supplied to xandora.net</h1>

<p>If you are concerned about how personal data is processed by xandora.net, please do
not hesitate to bring such concerns to the attention of xandora.net at the contact
details set out above.</p>

<h1>Collection and use of technical information</h1>

<p>This website does use cookies – a small file containing a string of characters
that is sent to your computer to identify your browser – including temporary
“session” cookies which enable a visitor’s web browser to remember which pages
on this website have already been visited. Visitors can use this website with
no substantial loss of functionality if cookies are disabled from the web
browser.</p>

<p>Technical details in connection with visits to our website may be logged by us
or a third party for our statistical purposes. No information is collected that
could be used by us to identify website visitors. The technical details logged
are confined to the following types of information:</p>

<ul>
<li>the Internet Protocol address or gateway of the visitor’s web server 
<li>the previous website address from which the visitor reached us 
<li>clickstream data which shows the traffic of visitors around this web site
(for example pages accessed and documents downloaded) 
<li>the type of web browser used by the visitor 
<li>the operating system of the visitor’s computer 
<li>the screen resolution of the visitor’s computer monitor.
</ul>

<p>By supplementing our records, this information helps us learn things like what
pages are most attractive to our visitors and what kinds of offers our
customers like to see. Where a third party logs information on our behalf, we
control how that data may and may not be used.</p>

<p>xandora.net will make no attempt to identify individual visitors, or to associate
the technical details listed above with any individual. It is xandora.net’s policy
never to disclose such technical information in respect of individual website
visitors to any third party (apart from any third party providing services to
us which may record such data on our behalf and which is bound by
confidentiality provisions in this regard), unless obliged or permitted to
disclose such information by a rule of law. </p>

<p>The technical information will be used only by xandora.net, and only for;
statistical and other administrative purposes. You should note that technical
details, which we cannot associate with any identifiable individual.</p>

<h1>Other websites</h1>

<p>xandora.net is not responsible for the content or privacy practices of other
websites accessible from this website via external links. These other websites
may place their own cookies or other files on your computer, collect data or
solicit personal information from you. Any external links to other websites are
clearly identifiable as such.</p>

<h1>Changes to this policy</h1>

<p>Please note that xandora.net may change this policy from time to time. Any amended
policy terms will be posted to the xandora.net website.</p>
</div>
